.docker-executor: &docker-executor
  tags:
    - docker

.only-run-on-branches: &only-run-on-branches
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: never
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
      when: always
    - when: never


.only-run-on-default-branch: &only-run-on-default-branch
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: always
    - when: never

image: hashicorp/terraform:0.14.5

stages:
  - compliance
  - security
  - publish

tflint:
  stage: compliance
  <<: *docker-executor
  script:
    - terraform fmt -recursive -check
  <<: *only-run-on-branches

static-analysis:
  stage: security
  <<: *docker-executor
  image: alpine:latest@sha256:08d6ca16c60fe7490c03d10dc339d9fd8ea67c6466dea8d558526b1330a85930
  before_script:
    - apk add --no-cache libc6-compat jq
    - KICS_VERSION=1.1.1
    - wget -q -c "https://github.com/Checkmarx/kics/releases/download/v${KICS_VERSION}/kics_${KICS_VERSION}_linux_x64.tar.gz" -O - | tar -xz --directory /usr/bin &>/dev/null
  script:
    - |
      kics -q /usr/bin/assets/queries -p ${PWD} -o ${PWD}/kics-results.json

      export TOTAL_SEVERITY_COUNTER=`jq .totalCounter kics-results.json`
      export SEVERITY_COUNTER_HIGH=`jq .severityCounters.HIGH kics-results.json`
      export SEVERITY_COUNTER_MEDIUM=`jq .severityCounters.MEDIUM kics-results.json`
      export SEVERITY_COUNTER_LOW=`jq .severityCounters.LOW kics-results.json`
      export SEVERITY_COUNTER_INFO=`jq .severityCounters.INFO kics-results.json`

      if [ "$SEVERITY_COUNTER_HIGH" -ge "1" ]; then
        echo "Please fix all $SEVERITY_COUNTER_HIGH HIGH SEVERITY COUNTERS" && exit 1;
      fi
  artifacts:
    name: kics-results.json
    expire_in: 8 hours
    paths:
      - kics-results.json
  needs: []
  <<: *only-run-on-branches

create-release:
  stage: publish
  <<: *docker-executor
  image: node:lts-alpine@sha256:51e341881c2b77e52778921c685e711a186a71b8c6f62ff2edfc6b6950225a2f
  script:
    - |
      npm i --no-lock @semantic-release/changelog@5.0.1 \
                @semantic-release/commit-analyzer@8.0.1 \
                @semantic-release/git@9.0.0 \
                @semantic-release/gitlab@6.0.9 \
                @semantic-release/release-notes-generator@9.0.1 \
                conventional-changelog-conventionalcommits@4.5.0 \
                semantic-release@17.3.8
    - semantic-release
  <<: *only-run-on-default-branch
